using Hydrix.Mapper.Attributes;
using Hydrix.Mapper.Configuration;
using Hydrix.Mapper.Mapping;
using System;
using Xunit;

namespace Hydrix.Mapper.UnitTests.Mapping
{
    /// <summary>
    /// Validates the Guid-to-string conventions and destination-level overrides exposed by the Hydrix mapper.
    /// </summary>
    /// <remarks>
    /// Each destination type is unique for its option combination so cached plans do not leak behavior between scenarios.
    /// </remarks>
    public class HydrixMapperGuidTests
    {
        /// <summary>
        /// Stores the stable Guid value reused across the formatting scenarios in this class.
        /// </summary>
        private static readonly Guid SampleGuid = new Guid(
            "a1b2c3d4-e5f6-7890-abcd-ef1234567890");

        /// <summary>
        /// Represents the non-nullable source model used by Guid conversion scenarios.
        /// </summary>
        private sealed class GuidSource
        {
            /// <summary>
            /// Gets or sets the Guid value mapped to the destination model.
            /// </summary>
            public Guid Id { get; set; }
        }

        /// <summary>
        /// Represents the nullable source model used by nullable Guid conversion scenarios.
        /// </summary>
        private sealed class NullableGuidSource
        {
            /// <summary>
            /// Gets or sets the nullable Guid value mapped to the destination model.
            /// </summary>
            public Guid? Id { get; set; }
        }

        /// <summary>
        /// Represents the destination model used by lowercase hyphenated Guid formatting.
        /// </summary>
        private sealed class DtoGlobalDLower
        {
            /// <summary>
            /// Gets or sets the string representation generated by the mapper.
            /// </summary>
            public string Id { get; set; }
        }

        /// <summary>
        /// Represents the destination model used by uppercase hyphenated Guid formatting.
        /// </summary>
        private sealed class DtoGlobalDUpper
        {
            /// <summary>
            /// Gets or sets the string representation generated by the mapper.
            /// </summary>
            public string Id { get; set; }
        }

        /// <summary>
        /// Represents the destination model used by Guid format <c>N</c>.
        /// </summary>
        private sealed class DtoGlobalNLower
        {
            /// <summary>
            /// Gets or sets the string representation generated by the mapper.
            /// </summary>
            public string Id { get; set; }
        }

        /// <summary>
        /// Represents the destination model used by Guid format <c>B</c>.
        /// </summary>
        private sealed class DtoGlobalBLower
        {
            /// <summary>
            /// Gets or sets the string representation generated by the mapper.
            /// </summary>
            public string Id { get; set; }
        }

        /// <summary>
        /// Represents the destination model used by Guid format <c>P</c>.
        /// </summary>
        private sealed class DtoGlobalPLower
        {
            /// <summary>
            /// Gets or sets the string representation generated by the mapper.
            /// </summary>
            public string Id { get; set; }
        }

        /// <summary>
        /// Represents the destination model whose member overrides the global configuration to use Guid format <c>N</c>.
        /// </summary>
        private sealed class DtoAttrN
        {
            /// <summary>
            /// Gets or sets the Guid string forced to format <c>N</c> by the destination attribute.
            /// </summary>
            [MapConversion(GuidFormat = GuidFormat.N, OverrideGuid = true)]
            public string Id { get; set; }
        }

        /// <summary>
        /// Represents the destination model whose member overrides the global configuration to use Guid format <c>B</c>.
        /// </summary>
        private sealed class DtoAttrB
        {
            /// <summary>
            /// Gets or sets the Guid string forced to format <c>B</c> by the destination attribute.
            /// </summary>
            [MapConversion(GuidFormat = GuidFormat.B, OverrideGuid = true)]
            public string Id { get; set; }
        }

        /// <summary>
        /// Represents the destination model whose member overrides the global configuration to use Guid format <c>P</c>.
        /// </summary>
        private sealed class DtoAttrP
        {
            /// <summary>
            /// Gets or sets the Guid string forced to format <c>P</c> by the destination attribute.
            /// </summary>
            [MapConversion(GuidFormat = GuidFormat.P, OverrideGuid = true)]
            public string Id { get; set; }
        }

        /// <summary>
        /// Represents the destination model whose member forces uppercase Guid output.
        /// </summary>
        private sealed class DtoAttrDU
        {
            /// <summary>
            /// Gets or sets the uppercase Guid string produced by the mapper.
            /// </summary>
            [MapConversion(GuidFormat = GuidFormat.D, GuidCase = GuidCase.Upper, OverrideGuid = true)]
            public string Id { get; set; }
        }

        /// <summary>
        /// Represents the destination model whose member forces lowercase Guid output.
        /// </summary>
        private sealed class DtoAttrDL
        {
            /// <summary>
            /// Gets or sets the lowercase Guid string produced by the mapper.
            /// </summary>
            [MapConversion(GuidFormat = GuidFormat.D, GuidCase = GuidCase.Lower, OverrideGuid = true)]
            public string Id { get; set; }
        }

        /// <summary>
        /// Represents the destination model used by nullable Guid scenarios.
        /// </summary>
        private sealed class DtoNullableD
        {
            /// <summary>
            /// Gets or sets the nullable Guid string produced by the mapper.
            /// </summary>
            public string Id { get; set; }
        }

        /// <summary>
        /// Creates a mapper configured for the requested Guid format and casing.
        /// </summary>
        /// <param name="format">The Guid format that the mapper should apply.</param>
        /// <param name="guidCase">The casing convention that the mapper should apply.</param>
        /// <returns>A mapper instance configured for the requested Guid output.</returns>
        private static HydrixMapper CreateMapper(
            GuidFormat format,
            GuidCase guidCase = GuidCase.Lower)
        {
            var options = new HydrixMapperOptions();
            options.Guid.Format = format;
            options.Guid.Case = guidCase;

            return new HydrixMapper(
                options);
        }

        /// <summary>
        /// Verifies that the default <c>D</c> format generates a hyphenated lowercase Guid string.
        /// </summary>
        [Fact]
        public void Map_Guid_DefaultFormat_ProducesHyphenatedLowercase()
        {
            var dto = CreateMapper(
                GuidFormat.D).Map<DtoGlobalDLower>(
                new GuidSource
                {
                    Id = SampleGuid,
                });

            Assert.Equal(
                SampleGuid.ToString("D"),
                dto.Id);
        }

        /// <summary>
        /// Verifies that uppercase casing is applied when the global configuration requests it.
        /// </summary>
        [Fact]
        public void Map_Guid_FormatD_Uppercase_ProducesUppercase()
        {
            var dto = CreateMapper(
                GuidFormat.D,
                GuidCase.Upper).Map<DtoGlobalDUpper>(
                new GuidSource
                {
                    Id = SampleGuid,
                });

            Assert.Equal(
                SampleGuid.ToString("D").ToUpperInvariant(),
                dto.Id);
        }

        /// <summary>
        /// Verifies that Guid format <c>N</c> omits hyphens from the generated string.
        /// </summary>
        [Fact]
        public void Map_Guid_FormatN_ProducesNoHyphens()
        {
            var dto = CreateMapper(
                GuidFormat.N).Map<DtoGlobalNLower>(
                new GuidSource
                {
                    Id = SampleGuid,
                });

            Assert.Equal(
                SampleGuid.ToString("N"),
                dto.Id);
            Assert.DoesNotContain(
                "-",
                dto.Id);
        }

        /// <summary>
        /// Verifies that a destination attribute can override the global Guid format with <c>N</c>.
        /// </summary>
        [Fact]
        public void Map_Guid_AttributeFormatN_OverridesGlobal()
        {
            var dto = CreateMapper(
                GuidFormat.D).Map<DtoAttrN>(
                new GuidSource
                {
                    Id = SampleGuid,
                });

            Assert.Equal(
                SampleGuid.ToString("N"),
                dto.Id);
        }

        /// <summary>
        /// Verifies that Guid format <c>B</c> wraps the value with braces.
        /// </summary>
        [Fact]
        public void Map_Guid_FormatB_ProducesBraces()
        {
            var dto = CreateMapper(
                GuidFormat.B).Map<DtoGlobalBLower>(
                new GuidSource
                {
                    Id = SampleGuid,
                });

            Assert.StartsWith(
                "{",
                dto.Id);
            Assert.EndsWith(
                "}",
                dto.Id);
        }

        /// <summary>
        /// Verifies that a destination attribute can override the global Guid format with <c>B</c>.
        /// </summary>
        [Fact]
        public void Map_Guid_AttributeFormatB_ProducesBraces()
        {
            var dto = CreateMapper(
                GuidFormat.D).Map<DtoAttrB>(
                new GuidSource
                {
                    Id = SampleGuid,
                });

            Assert.StartsWith(
                "{",
                dto.Id);
        }

        /// <summary>
        /// Verifies that Guid format <c>P</c> wraps the value with parentheses.
        /// </summary>
        [Fact]
        public void Map_Guid_FormatP_ProducesParentheses()
        {
            var dto = CreateMapper(
                GuidFormat.P).Map<DtoGlobalPLower>(
                new GuidSource
                {
                    Id = SampleGuid,
                });

            Assert.StartsWith(
                "(",
                dto.Id);
            Assert.EndsWith(
                ")",
                dto.Id);
        }

        /// <summary>
        /// Verifies that a destination attribute can override the global Guid format with <c>P</c>.
        /// </summary>
        [Fact]
        public void Map_Guid_AttributeFormatP_ProducesParentheses()
        {
            var dto = CreateMapper(
                GuidFormat.D).Map<DtoAttrP>(
                new GuidSource
                {
                    Id = SampleGuid,
                });

            Assert.StartsWith(
                "(",
                dto.Id);
        }

        /// <summary>
        /// Verifies that a destination attribute can force uppercase Guid output even when the global configuration is lowercase.
        /// </summary>
        [Fact]
        public void Map_Guid_AttributeUpperCase_ProducesUppercase()
        {
            var dto = CreateMapper(
                GuidFormat.D).Map<DtoAttrDU>(
                new GuidSource
                {
                    Id = SampleGuid,
                });

            Assert.Equal(
                dto.Id,
                dto.Id.ToUpperInvariant());
        }

        /// <summary>
        /// Verifies that a destination attribute can force lowercase Guid output even when the global configuration is uppercase.
        /// </summary>
        [Fact]
        public void Map_Guid_AttributeLowerCase_ProducesLowercase()
        {
            var dto = CreateMapper(
                GuidFormat.D,
                GuidCase.Upper).Map<DtoAttrDL>(
                new GuidSource
                {
                    Id = SampleGuid,
                });

            Assert.Equal(
                dto.Id,
                dto.Id.ToLowerInvariant());
        }

        /// <summary>
        /// Verifies that a null nullable Guid source produces a null destination string.
        /// </summary>
        [Fact]
        public void Map_NullableGuid_WhenNull_ProducesNull()
        {
            var dto = CreateMapper(
                GuidFormat.D).Map<DtoNullableD>(
                new NullableGuidSource
                {
                    Id = null,
                });

            Assert.Null(
                dto.Id);
        }

        /// <summary>
        /// Verifies that a nullable Guid source with a value is formatted the same way as a non-nullable Guid.
        /// </summary>
        [Fact]
        public void Map_NullableGuid_WhenHasValue_ProducesString()
        {
            var dto = CreateMapper(
                GuidFormat.D).Map<DtoNullableD>(
                new NullableGuidSource
                {
                    Id = SampleGuid,
                });

            Assert.Equal(
                SampleGuid.ToString("D"),
                dto.Id);
        }

        /// <summary>
        /// Verifies that <see cref="Guid.Empty"/> is formatted correctly by the default Guid conventions.
        /// </summary>
        [Fact]
        public void Map_EmptyGuid_ProducesExpectedString()
        {
            var dto = CreateMapper(
                GuidFormat.D).Map<DtoGlobalDLower>(
                new GuidSource
                {
                    Id = Guid.Empty,
                });

            Assert.Equal(
                Guid.Empty.ToString("D"),
                dto.Id);
        }
    }
}
